\documentclass{article}
\pdfoptionpdfminorversion=5
\usepackage[textwidth=6in]{geometry}
\usepackage{graphicx}
\usepackage{/Users/eleanorbrush/Documents/custom2}
\usepackage{wasysym}
\usepackage{color}
\usepackage[numbers,sort&compress]{natbib}
\newcommand{\ra}[1]{\renewcommand{\arraystretch}{#1}}
%% for inline R code: if the inline code is not correctly parsed, you will see a message
\newcommand{\rinline}[1]{SOMETHING WRONG WITH knitr}
\newtheorem{rexample}{Code}[section]

\begin{document}

<<setup, include=FALSE>>=
library(knitr)
opts_chunk$set(fig.path='figure/minimal-',fig.align='center', fig.show='hold',cache.path='cache/latex-', size = "footnotesize")
options(formatR.arrow=TRUE,width=90)
knit_hooks$set(rexample = function(before, options, envir) {
  if (before) sprintf('\\begin{rexample}\\label{%s}\\hfill{}', options$label) else '\\end{rexample}'
})
@

<< get_code, echo = FALSE, cache = FALSE >>=
read_chunk("continuous_traits_knitr.R")
@

<<integral, echo = FALSE>>=
@

<<check, echo =TRUE, eval = FALSE>>=
x = runif(10)
x[1]
@

\section{Introduction}


\section{Question}
\begin{enumerate}
\item H1 Song learning can decelerate speciation by allowing for genetically diverse birds to mate with each other, maintaining gene flow between subpopulations that might either begin to diverge
\item H2 Song learning can accelerate speciation by increasing standing genetic variation, which would allow for quicker divergence once new selection pressures arise \cite{Lachlan:2004tg}
\item H3 Song learning can accelerate speciation because culturally inherited traits can evolve more quickly than genetically inherited ones \cite{Irwin:2012hc}
\end{enumerate}

\begin{table}
\caption{\label{summmary_previous} Summary of choices made in previous models}
\ra{1.3}
\begin{tabular}{@{}l@{}llllll}
&\citet{Lachlan:2004tg}
\\ \male trait(s) & allele A  / a: song predisposition
 \\ & song
\\ How \male trait is learned 
\\ Inherited 
\\\female trait(s) 
\\How \female trait is learned 
\\Inherited
\\ Errors
\\ Population structure
\\ Mating structure
\\ \female preference
\\ Selection
\end{tabular}
\end{table}

\section{Goals}

\section{Model}

\subsection{Continuous traits }

Each male has a song and each female has preference for a particular song. She will mate with males with songs other than her preferred song, but the probability of her doing so decreases as the potential mate's song gets less similar to her preferred song. Each female mates once and chooses a male according to her preferences and the distribution of songs present in the population. Each male, therefore, may breed multiple times or not at all. We assume that generations are non-overlapping, so once the adults breed they die and we can shift our focus to the new generation. To begin with, we assume that males acquire their songs from their fathers at birth and females acquire their preferences from their mothers at birth. We further assume an unbiased sex ratio. Before the new generation mates, each male has a small probability of ``mutating" its song. This can be interpreted as a learning error or as innovation. After mutation, the new males and females mate. 

Mathematically, each male has a song $x\in \R$ and each female has a preference $y\in\R$. The probability density of the male songs will be written $P_\text{m}(x)$ and the probability density of female preferences will be written $P_\text{f}(y)$. The preference of a female with preference $y$ mates for a male with song $x$ is 
\begin{equation*}
f_y(x)=\frac{1}{\sqrt{2 \pi \sigma^2}}\exp\left(-\frac{(x-y)^2}{2\sigma^2}\right),
\end{equation*}
which is maximal when $x=y$ and decreases as $|x-y|$ increases. The probability that a female with preference $y$ choose a male with song $x$ is 
\begin{equation*}
\frac{P_\text{m}(x)f_y(x)}{\int_\R P_\text{m}(x')f_y(x')dx'},
\end{equation*}
so the probability of a $(x,y)$ pair mating is then
\begin{equation*}
P_\text{mate}(x,y)=\frac{P_\text{f}(y)P_\text{m}(x)f_y(x)}{\int_\R P_\text{m}(x')f_y(x')dx'}=\frac{P_\text{f}(y)P_\text{m}(x)f_y(x)}{Z_y},
\end{equation*}
where $Z_y$ is the normalizing factor $\int_\R P_\text{m}(x')f_y(x')dx'$.
Each such pair will produce a male with song $x$ and a female with preference $y$. Before mating, the male's song changes to $x-\delta_\text{mut}$ with probability $p_\text{mut}/2$ and to $x+\delta_\text{mut}$ with probability $p_\text{mut}/2$. Under these assumptions, the probability density of female preferences does not change over time:
\begin{equation*}
P_\text{f}(y,t+1)=P_\text{f}(y,t).
\end{equation*}
The probability density of male songs in the next generation, before mutating and after mutating, follows
\begin{align*}
P_\text{m}(x,t+1/2)&=\int_\R P_\text{mate}(x,y,t) dy
\\P_\text{m}(x,t+1)&=(1-p_\text{mut})P_\text{m}(x,t+1/2)+p_\text{mut}/2P_\text{m}(x-\delta_\text{mut},t+1/2)+p_\text{mut}/2P_\text{m}(x+\delta_\text{mut},t+1/2)
\end{align*}
 (Population dynamics are modeled in Code \ref{dynamics}. Global and / or needed parameters are given in Code \ref{parameters}.)

<<dynamics, echo =TRUE, rexample = TRUE >>=
@ 

<<parameters, echo =TRUE, rexample=TRUE >>=
@ 

We start with mixtures of normal distributions of both male and female:
\begin{align*}
P_\text{f}(y,0)&=p_\text{f}\frac{1}{\sqrt{2\pi\sigma_\text{f}^2}}\exp\left(-\frac{(y+1)^2}{2\sigma_\text{f}^2}\right)+(1-p_\text{f})\frac{1}{\sqrt{2\pi\sigma_\text{f}^2}}\exp\left(-\frac{(y-1)^2}{2\sigma_\text{f}^2}\right)
\\P_\text{m}(x,0)&=p_\text{m}\frac{1}{\sqrt{2\pi\sigma_\text{m}^2}}\exp\left(-\frac{(x+1)^2}{2\sigma_\text{m}^2}\right)+(1-p_\text{m})\frac{1}{\sqrt{2\pi\sigma_\text{m}^2}}\exp\left(-\frac{(x-1)^2}{2\sigma_\text{m}^2}\right)
\end{align*}
Even with a continuous distribution of female preferences, we find that after several generations, the male song distribution is concentrated in several discrete peaks (Figure \ref{fig:plot_peaks}). (Parameters and initial conditions given in Code \ref{peaks}.)

There are three critical parameters:
\begin{table}
\caption{\label{parameters} Parameters}
\ra{1.3}
\begin{tabular}{llllll}
$\sigma^2$ & width of female preference function
\\$\sigma_\text{f}^2$ & variance of female preferences within each population
\\$\sigma_\text{m}^2$ & variance of male traits within each population
\end{tabular}
\end{table}

<<peaks, echo = TRUE, cache = TRUE, rexample=TRUE >>=
@

<< plot_peaks, fig.width=5, fig.height=5, echo = FALSE, fig.cap = 'Probability  density of male songs. Notice the discrete peaks. ' >>=
t=60
plot(mrange,Pm[,t],type='l',xlab = 'Song',ylab = 'Probability density',main = c('T=',t))
@

Mutations give rise to a small number of males with song traits that are slightly higher (lower) than the rest of the population. The ``edge" females that most prefer these extreme songs have limited options because they do not like the songs most males are singing. They therefore mate with the new ``edge" males with very high probability, which leads to a very fast increase of these songs. As mutations continue to generate new songs, extreme songs will be selected for at the expense of similar songs closer to the middle of the song range. Ultimately, this results in a number of discrete songs at high density.

Ignoring mutations for the moment, the rate of change of the probability density of a particular song is given by 
\begin{equation}
\frac{P_\text{m}(x,t+1)}{P_\text{m}(x,t)}= \int _\R\frac{ P_\text{f}(y)f_y(x)}{Z_y}dy \label{growth}
\end{equation}
This shows that the normalizing factor $Z_y$ affects how the density of male songs changes from one generation to the next: if a male is recognized by females with very few options (small $Z_y$), then the density of that song will increase more than the song a male recognized by females with many options (large $Z_y$) (Figure \ref{fig:explanation_plot}).

<<explanation, echo = FALSE, cache = TRUE>>=
@

<<explanation_plot, echo=FALSE, cache= TRUE, fig.cap = "The growth rate of songs depends on the females' available choices. On the left we plot the logarithm of the growth rate, highlighting two song traits. On the right we plot the integrand in Equation for growth rate for the same two song traits." >>=
par(mfrow=c(1,2))
i1 = 1133;
i2 = 1140;
r = 1100:1160

plot(mrange[r],log(growth_rate[r]),type='l',xlab='Song',ylab='Log(growth rate)',main=c('T=',t_peak))
abline(v=mrange[i1],col='red')
abline(v=mrange[i2],col='blue')

plot(frange,preferences[i2,]*Pf[,t_peak]/female_tots,type='l',	
	col='blue',xlab='Preference',ylab='Probability of being chosen')
lines(frange,preferences[i1,]*Pf[,t_peak]/female_tots,col='red')
w=which.max(preferences[i2,]*Pf[,t_peak]/female_tots)
@

This model was built to study whether song diversity can be maintained when two populations come back together. However, even within one population there are interesting dynamics.
\begin{enumerate}
\item There can be many discrete ``popular" songs when $\sigma_\text{m}^2$  is small, $\sigma_\text{f}^2$ is high, and $\sigma^2$ is intermediate.
\item When the equilibrium population is unimodal, there is an interesting interaction between $\sigma^2$ and $\sigma_\text{f}^2$: At low $\sigma^2$ and low $\sigma_\text{f}^2$, the males are even more narrowly distributed than the females because the male trait preferred by the most females does way better than anyone else. At low $\sigma^2$ and high $\sigma_\text{f}^2$, the male distribution matches the female distribution. At high $\sigma^2$, $\sigma_\text{f}^2$ does not matter and the male distribution is moderately narrow because average males can mate with most females. 
\end{enumerate}

\bibliographystyle{plainnat}
\bibliography{song_learning_evolution}


\end{document}
