# source('peaks_in_mech_3_and_5.R')
# source('peak_example.R')
# source('pearson_kurtosis.R')
# source('mutation_test.R')
source('step_pref_dist.R')
source('step_song_dist.R')
source('step_pref_function.R')